spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hnu_test
    username: root
    password: 142857
mybatis:
  configuration:
    map-underscore-to-camel-case: true
